entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: anthonyrov@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      keyType: EC256
        
providers:
  docker:
    exposedByDefault: false
    network: traefik_network
